In [ ]:
!pip install unsloth

Collecting unsloth
  Downloading unsloth-2026.9.7-py3-none-any.whl.metadata (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 3.9 MB/s eta 0:00:00
Collecting unsloth_zoo>=2026.9.6 (from unsloth)
  Downloading unsloth_zoo-2026.9.6-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.48.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from unsloth) (26.3)
Requirement already satisfied: torch<2.13.0,>=2.4.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.11.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.26.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from unsloth) (5.9.5)
Collecting tyro (from unsloth)
  Downloading tyro-1.0.16-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from unsloth) (5.29.6)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth)
  Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (3.6.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.2.2)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.14.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.20.0)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.29.0)
Collecting hf_transfer (from unsloth)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: diffusers in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.40.0)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.27.2)
Requirement already satisfied: pydantic in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.13.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from unsloth) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.6.0)
Collecting structlog>=24.1.0 (from unsloth)
  Downloading structlog-26.1.0-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (8.5.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from unsloth) (13.9.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from accelerate>=0.34.1->unsloth) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.32.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.1)
Collecting dill<0.4.1,>=0.3.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.0.1)
Collecting multiprocess<0.70.17 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Downloading multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.9.0,>=2023.1.0 (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Downloading fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.4.5)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth) (2025.11.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.12.0->unsloth) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer>=0.12.0->unsloth) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->unsloth) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->unsloth) (2.21.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.9.6->unsloth)
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.9.6->unsloth)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo>=2026.9.6->unsloth) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2026.9.6->unsloth)
  Downloading msgspec-0.21.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.13/dist-packages (from diffusers->unsloth) (9.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (0.4.4)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth) (0.18.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth) (4.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch<2.13.0,>=2.4.0->unsloth) (1.8.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->unsloth) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch<2.13.0,>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib_metadata->diffusers->unsloth) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch<2.13.0,>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Downloading unsloth-2026.9.7-py3-none-any.whl (23.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 89.2 MB/s eta 0:00:00
Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 22.0 MB/s eta 0:00:00
Downloading datasets-4.3.0-py3-none-any.whl (506 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 44.5 MB/s eta 0:00:00
Downloading structlog-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 kB 8.6 MB/s eta 0:00:00
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 110.6 MB/s eta 0:00:00
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 36.1 MB/s eta 0:00:00
Downloading unsloth_zoo-2026.9.6-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 84.5 MB/s eta 0:00:00
Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 106.0 MB/s eta 0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 101.1 MB/s eta 0:00:00
Downloading tyro-1.0.16-py3-none-any.whl (216 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.9/216.9 kB 22.4 MB/s eta 0:00:00
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 13.1 MB/s eta 0:00:00
Downloading fsspec-2025.9.0-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 21.3 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py312-none-any.whl (146 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.7/146.7 kB 15.4 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 108.3 MB/s eta 0:00:00
Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 76.2 MB/s eta 0:00:00
Downloading cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Downloading msgspec-0.21.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (225 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.1/225.1 kB 18.8 MB/s eta 0:00:00
Installing collected packages: torchao, structlog, msgspec, hf_transfer, fsspec, dill, tyro, multiprocess, tokenizers, datasets, xformers, transformers, cut_cross_entropy, bitsandbytes, trl, unsloth_zoo, unsloth
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.12.0
    Uninstalling fsspec-2025.12.0:
      Successfully uninstalled fsspec-2025.12.0
  Attempting uninstall: dill
    Found existing installation: dill 0.4.1
    Uninstalling dill-0.4.1:
      Successfully uninstalled dill-0.4.1

In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

In [13]:
from google.colab import userdata
import openai
client = openai.OpenAI(api_key=userdata.get('OPENAI_API_KEY'))

In [14]:
import json

def generate_qa_pairs(source_text, n_pairs=20):
    prompt = f"""You are creating training data for fine-tuning an AI model on FDA/GxP regulatory compliance knowledge.

Read the source text below and generate exactly {n_pairs} question-answer pairs based ONLY on facts in this text. Do not invent information not present in the source.

Rules:
- Questions should be realistic things a compliance professional would ask
- Answers should be accurate, concise (2-4 sentences), and professional in tone
- Vary question types: definitions, "what does X require", "how do I comply with Y", scenario-based

Return ONLY a JSON array, no other text, in this exact format:
[{{"instruction": "question here", "input": "", "output": "answer here"}}]

Source text:
{source_text}
"""
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )
    raw = response.choices[0].message.content
    # strip markdown code fences if the model adds them
    raw = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    return json.loads(raw)

In [15]:
qa_pairs = generate_qa_pairs(source_text, n_pairs=20)
print(len(qa_pairs))
print(qa_pairs[0])  # inspect one example

19
{'instruction': 'What do closed systems require for electronic records?', 'input': '', 'output': 'Closed systems must employ procedures and controls to ensure the authenticity, integrity, and confidentiality of electronic records, ensuring that signers cannot easily repudiate the signed records.'}

In [8]:
source_text = """
Persons who use closed systems to create, modify, maintain, or transmit electronic records shall employ procedures and controls designed to ensure the authenticity, integrity, and, when appropriate, the confidentiality of electronic records, and to ensure that the signer cannot readily repudiate the signed record as not genuine. Such procedures and controls shall include the following:
(a) Validation of systems to ensure accuracy, reliability, consistent intended performance, and the ability to discern invalid or altered records.
(b) The ability to generate accurate and complete copies of records in both human readable and electronic form suitable for inspection, review, and copying by the agency.
(c) Protection of records to enable their accurate and ready retrieval throughout the records retention period.
"""

In [16]:
source_chunks = [
"""
Persons who use closed systems to create, modify, maintain, or transmit electronic records shall employ procedures and controls designed to ensure the authenticity, integrity, and, when appropriate, the confidentiality of electronic records, and to ensure that the signer cannot readily repudiate the signed record as not genuine. Such procedures and controls shall include the following:
(a) Validation of systems to ensure accuracy, reliability, consistent intended performance, and the ability to discern invalid or altered records.
(b) The ability to generate accurate and complete copies of records in both human readable and electronic form suitable for inspection, review, and copying by the agency.
(c) Protection of records to enable their accurate and ready retrieval throughout the records retention period.
"""
    """(d) Limiting system access to authorized individuals.""",
    """(e) Use of secure, computer-generated, time-stamped audit trails to independently record the date and time of operator entries and actions that create, modify, or delete electronic records. Record changes shall not obscure previously recorded information. Such audit trail documentation shall be retained for a period at least as long as that required for the subject electronic records and shall be available for agency review and copying.""",
    """Use of operational system checks to enforce permitted sequencing of steps and events, as appropriate.""",
    """Use of authority checks to ensure that only authorized individuals can use the system, electronically sign a record, access the operation or computer system input or output device, alter a record, or perform the operation at hand.""",
]

In [17]:
import time

all_qa_pairs = []

for i, chunk in enumerate(source_chunks):
    print(f"Generating from chunk {i+1}/{len(source_chunks)}...")
    pairs = generate_qa_pairs(chunk, n_pairs=25)
    all_qa_pairs.extend(pairs)
    time.sleep(2)  # small pause, avoids hitting rate limits

print(f"Total pairs generated: {len(all_qa_pairs)}")

Generating from chunk 1/4...
Generating from chunk 2/4...
Generating from chunk 3/4...
Generating from chunk 4/4...
Total pairs generated: 91

In [18]:
import random
for pair in random.sample(all_qa_pairs, 5):
    print("Q:", pair['instruction'])
    print("A:", pair['output'])
    print("---")

Q: How can I confirm the reliability of my electronic record systems?
A: To confirm the reliability of electronic record systems, conduct regular validations, perform system checks, and ensure that the systems consistently perform their intended functions without errors.
---
Q: What is the significance of generating copies in both forms (human-readable and electronic)?
A: Generating copies in both human-readable and electronic forms ensures that records can be accessed and reviewed by various stakeholders, including regulatory agencies, facilitating compliance and audit processes.
---
Q: What action must be taken when an electronic record is deleted?
A: When an electronic record is deleted, the audit trail must still reflect the action and document the date and time of the deletion.
---
Q: How can I ensure compliance with authority checks?
A: To ensure compliance with authority checks, establish clear policies for user access, regularly audit user permissions, and provide training on the importance of following these protocols.
---
Q: What should I document regarding operational system checks?
A: You should document the procedures for operational system checks, including the specific steps being checked, the logic behind the sequencing, and any automation tools used. This documentation is vital for audits and compliance verification.
---

In [19]:
with open('qa_pairs.jsonl', 'w') as f:
    for pair in all_qa_pairs:
        f.write(json.dumps(pair) + '\n')

print("Saved", len(all_qa_pairs), "pairs")

Saved 91 pairs

In [20]:
print(f"Total pairs generated: {len(all_qa_pairs)}")

Total pairs generated: 91

In [21]:
import random
for pair in random.sample(all_qa_pairs, 5):
    print("Q:", pair['instruction'])
    print("A:", pair['output'])
    print("---")

Q: How should organizations manage access to audit trails?
A: Organizations should implement strict access controls to manage who can view or modify audit trails, ensuring that only authorized personnel can access this sensitive information.
---
Q: What is the purpose of time-stamped audit trails?
A: Time-stamped audit trails are used to independently record operator actions, providing a clear timeline of when specific entries and modifications to electronic records were made.
---
Q: What type of systems require operational system checks?
A: Operational system checks are typically required in systems where the sequence of operations is critical to compliance, such as in manufacturing, laboratory procedures, and quality control processes.
---
Q: What role does documentation play in FDA/GxP compliance?
A: Documentation plays a critical role in FDA/GxP compliance as it provides evidence of adherence to regulations and helps ensure the integrity and reliability of electronic records.
---
Q: How do operational system checks support risk management?
A: Operational system checks support risk management by identifying and mitigating errors before they occur, thereby reducing the likelihood of non-compliance and enhancing overall process reliability.
---

In [22]:
with open('qa_pairs.jsonl', 'w') as f:
    for pair in all_qa_pairs:
        f.write(json.dumps(pair) + '\n')

print("Saved", len(all_qa_pairs), "pairs")

Saved 91 pairs

In [23]:
random.shuffle(all_qa_pairs)
split_idx = int(len(all_qa_pairs) * 0.85)
train_pairs = all_qa_pairs[:split_idx]
test_pairs = all_qa_pairs[split_idx:]

print(f"Train: {len(train_pairs)}, Test: {len(test_pairs)}")

with open('train.jsonl', 'w') as f:
    for pair in train_pairs:
        f.write(json.dumps(pair) + '\n')

with open('test.jsonl', 'w') as f:
    for pair in test_pairs:
        f.write(json.dumps(pair) + '\n')

Train: 77, Test: 14

In [25]:
!pip install unsloth

Collecting unsloth
  Downloading unsloth-2026.9.11-py3-none-any.whl.metadata (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.1/81.1 kB 4.2 MB/s eta 0:00:00
Collecting unsloth_zoo>=2026.9.7 (from unsloth)
  Downloading unsloth_zoo-2026.9.7-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.48.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from unsloth) (26.3)
Requirement already satisfied: torch<2.13.0,>=2.4.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.11.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.26.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from unsloth) (5.9.5)
Collecting tyro (from unsloth)
  Downloading tyro-1.0.16-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from unsloth) (5.29.6)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth)
  Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (3.6.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.2.2)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.14.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.20.0)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.29.0)
Collecting hf_transfer (from unsloth)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: diffusers in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.40.0)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (0.27.2)
Requirement already satisfied: pydantic in /usr/local/lib/python3.13/dist-packages (from unsloth) (2.13.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from unsloth) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (from unsloth) (1.6.0)
Collecting structlog>=24.1.0 (from unsloth)
  Downloading structlog-26.1.0-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.13/dist-packages (from unsloth) (8.5.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from unsloth) (13.9.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from accelerate>=0.34.1->unsloth) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.32.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.1)
Collecting dill<0.4.1,>=0.3.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.0.1)
Collecting multiprocess<0.70.17 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Downloading multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.9.0,>=2023.1.0 (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Downloading fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0->unsloth) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch<2.13.0,>=2.4.0->unsloth) (3.4.5)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<2.13.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth) (2025.11.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.12.0->unsloth) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer>=0.12.0->unsloth) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->unsloth) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->unsloth) (2.21.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.9.7->unsloth)
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.9.7->unsloth)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from unsloth_zoo>=2026.9.7->unsloth) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2026.9.7->unsloth)
  Downloading msgspec-0.21.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.13/dist-packages (from diffusers->unsloth) (9.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic->unsloth) (0.4.4)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth) (0.18.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from tyro->unsloth) (4.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch<2.13.0,>=2.4.0->unsloth) (1.8.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->unsloth) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch<2.13.0,>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib_metadata->diffusers->unsloth) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch<2.13.0,>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Downloading unsloth-2026.9.11-py3-none-any.whl (24.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.4/24.4 MB 85.2 MB/s eta 0:00:00
Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 19.8 MB/s eta 0:00:00
Downloading datasets-4.3.0-py3-none-any.whl (506 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 27.5 MB/s eta 0:00:00
Downloading structlog-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 kB 5.8 MB/s eta 0:00:00
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 67.4 MB/s eta 0:00:00
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 23.2 MB/s eta 0:00:00
Downloading unsloth_zoo-2026.9.7-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 64.3 MB/s eta 0:00:00
Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 83.9 MB/s eta 0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 66.2 MB/s eta 0:00:00
Downloading tyro-1.0.16-py3-none-any.whl (216 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.9/216.9 kB 25.7 MB/s eta 0:00:00
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 9.7 MB/s eta 0:00:00
Downloading fsspec-2025.9.0-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 22.7 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py312-none-any.whl (146 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.7/146.7 kB 16.9 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 122.6 MB/s eta 0:00:00
Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 89.3 MB/s eta 0:00:00
Downloading cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Downloading msgspec-0.21.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (225 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.1/225.1 kB 23.9 MB/s eta 0:00:00
Installing collected packages: torchao, structlog, msgspec, hf_transfer, fsspec, dill, tyro, multiprocess, tokenizers, datasets, xformers, transformers, cut_cross_entropy, bitsandbytes, trl, unsloth_zoo, unsloth
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.12.0
    Uninstalling fsspec-2025.12.0:
      Successfully uninstalled fsspec-2025.12.0
  Attempting uninstall: dill
    Found existing installation: dill 0.4.1
    Uninstalling dill-0.4.1:
      Successfully uninstalled dill-0.4.1

In [26]:
from unsloth import FastLanguageModel
import torch

max_seq_length = 2048
dtype = None  # auto-detect

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = True,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.9.11: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3-8b-bnb-4bit as a legacy tokenizer.

In [27]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,  # rank — size of the "notebook", higher = more capacity but slower
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

Unsloth 2026.9.11 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

In [28]:
model.print_trainable_parameters()

trainable params: 41,943,040 || all params: 8,072,204,288 || trainable%: 0.5196

In [29]:
import os
print(os.path.exists('train.jsonl'), os.path.exists('test.jsonl'))

True True

In [30]:
from datasets import load_dataset

alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

EOS_TOKEN = tokenizer.eos_token

def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs = examples["input"]
    outputs = examples["output"]
    texts = []
    for instruction, input_, output in zip(instructions, inputs, outputs):
        text = alpaca_prompt.format(instruction, input_, output) + EOS_TOKEN
        texts.append(text)
    return {"text": texts}

dataset = load_dataset("json", data_files="train.jsonl", split="train")
dataset = dataset.map(formatting_prompts_func, batched=True)

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/77 [00:00<?, ? examples/s]

In [31]:
from trl import SFTTrainer
from transformers import TrainingArguments

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,        # enough for a 77-example demo dataset
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/77 [00:00<?, ? examples/s]

In [32]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 77 | Num Epochs = 6 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:4091: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:4091: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:4091: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:4091: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  return original(name)

Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-60/tokenizer_config.json.

In [33]:
import json

FastLanguageModel.for_inference(model)

test_data = []
with open('test.jsonl', 'r') as f:
    for line in f:
        test_data.append(json.loads(line))

print(f"Loaded {len(test_data)} test questions")

Loaded 14 test questions

In [34]:
def generate_answer(instruction, input_text=""):
    prompt = alpaca_prompt.format(instruction, input_text, "")
    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens=150, use_cache=True)
    decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    # extract just the response part, after "### Response:"
    response = decoded.split("### Response:")[-1].strip()
    return response

In [35]:
finetuned_answers = []
for item in test_data:
    answer = generate_answer(item['instruction'], item.get('input', ''))
    finetuned_answers.append(answer)
    print("Q:", item['instruction'])
    print("Fine-tuned A:", answer)
    print("---")

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What should an organization do to ensure compliance with audit trail requirements?
Fine-tuned A: To ensure compliance, organizations should establish policies and procedures for audit trails, provide training on their use, and regularly monitor and review them to detect any unauthorized modifications.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are operational system checks?
Fine-tuned A: Operational system checks are procedures that verify the correct sequence of operations in a process, ensuring that all steps are taken in the designated order to maintain compliance and quality.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are the consequences of inadequate system validation?
Fine-tuned A: Inadequate system validation can lead to non-compliance, potential fines, and increased risk of errors or incidents that may harm patient safety or product integrity.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are the consequences of not implementing authority checks?
Fine-tuned A: Not implementing authority checks can lead to unauthorized access and actions, which can jeopardize data integrity, compliance, and overall system security.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: Why are operational system checks important for compliance?
Fine-tuned A: Operational system checks are important for compliance as they help ensure that procedures are being followed correctly, which is crucial for maintaining regulatory adherence and preventing deviations that could lead to non-compliance.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: Who is responsible for managing authority checks?
Fine-tuned A: The organization is responsible for managing authority checks, including establishing policies, implementing procedures, and ensuring that personnel comply with these protocols.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How long must audit trail documentation be retained according to FDA/GxP regulations?
Fine-tuned A: Audit trail documentation must be retained for a period at least as long as the electronic records they validate, as per FDA/GxP regulations.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How can I ensure that my procedures are effective?
Fine-tuned A: To ensure that your procedures are effective, regularly monitor their performance, conduct audits, and make adjustments as necessary to address any issues identified.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What actions should be taken to prepare for an inspection of electronic records?
Fine-tuned A: To prepare for an inspection of electronic records, agencies should ensure that systems are compliant with regulatory requirements, documentation is accurate and complete, and training has been provided on recordkeeping protocols.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What is the purpose of enforcing permitted sequencing?
Fine-tuned A: Enforcing permitted sequencing is important for ensuring that operations are performed in the correct order, which is crucial for maintaining process integrity, compliance, and overall product quality.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What does FDA/GxP require for changes made to electronic records?
Fine-tuned A: FDA/GxP requires that all changes to electronic records are documented with audit trails that accurately reflect the date and time of the action.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How often should operational system checks be reviewed?
Fine-tuned A: Operational system checks should be reviewed regularly, with the frequency determined by organizational policies and the level of risk associated with the processes.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What should be included in procedures for electronic records?
Fine-tuned A: Procedures for electronic records should include controls for system access, record generation and handling, record integrity checks, and the ability to generate accurate copies of records as required by regulatory agencies.
---
Q: Are audit trails optional under FDA/GxP regulations?
Fine-tuned A: No, audit trails are not optional under FDA/GxP regulations as they are crucial for compliance and investigations.
---

In [36]:
with open('finetuned_answers.json', 'w') as f:
    json.dump(finetuned_answers, f)
print("Saved fine-tuned answers")

Saved fine-tuned answers

In [37]:
model.disable_adapter_layers()

In [38]:
base_answers = []
for item in test_data:
    answer = generate_answer(item['instruction'], item.get('input', ''))
    base_answers.append(answer)
    print("Q:", item['instruction'])
    print("Base A:", answer)
    print("---")

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What should an organization do to ensure compliance with audit trail requirements?
Base A: An organization should ensure that all changes made to data are recorded and that the records of these changes are retained for the appropriate amount of time.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are operational system checks?
Base A: Operational system checks are checks that are performed to ensure the correct operation of the system. These checks are designed to detect and correct any errors or issues that may arise during the system's operation. The checks are performed regularly, and they are designed to ensure that the system is functioning correctly and that any issues are addressed as quickly as possible.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are the consequences of inadequate system validation?
Base A: Inadequate system validation can lead to the following consequences:
1. System failures that may cause loss of lives, property, and money.
2. Poor system performance and low efficiency.
3. System security breaches.
4. Poor system usability.
5. High maintenance costs.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are the consequences of not implementing authority checks?
Base A: The consequences of not implementing authority checks are that an attacker could exploit the lack of security measures in place. If there are no checks in place, then an attacker could potentially gain access to sensitive information or cause damage to the system. This could lead to a security breach, which could result in financial loss, damage to reputation, and legal issues.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: Why are operational system checks important for compliance?
Base A: Operational system checks are important for compliance because they ensure that the system is functioning correctly and that data is being stored and processed correctly. This is important for compliance because it ensures that the system is meeting the necessary standards and regulations, such as data security and privacy laws. Additionally, operational system checks can help identify any potential issues or risks with the system, which can be addressed before they become a problem. This helps to ensure that the system is always functioning correctly and that any issues are quickly addressed.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: Who is responsible for managing authority checks?
Base A: The system administrator is responsible for managing authority checks.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How long must audit trail documentation be retained according to FDA/GxP regulations?
Base A:
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How can I ensure that my procedures are effective?
Base A: To ensure that my procedures are effective, I will need to evaluate them. This can be done by measuring the effectiveness of the procedures. By measuring the effectiveness of the procedures, I can determine if the procedures are effective. If the procedures are not effective, I will need to modify them. If the procedures are effective, I will need to continue using them. By evaluating the effectiveness of the procedures, I can ensure that they are effective.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What actions should be taken to prepare for an inspection of electronic records?
Base A: The first step is to ensure that all electronic records are properly stored and organized. This includes ensuring that all records are backed up regularly and that the backup system is functioning properly. Additionally, all records should be properly labeled and dated, and any records that are no longer needed should be properly disposed of.

The second step is to ensure that all electronic records are properly secured. This includes ensuring that all records are password protected and that the password is strong and secure. Additionally, all records should be encrypted and any records that are stored on portable devices should be password protected and encrypted.

The third step is to ensure that all electronic records are properly accessible. This includes ensuring that all records can be easily accessed by authorized personnel, and that any records that are stored
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What is the purpose of enforcing permitted sequencing?
Base A: The purpose of enforcing permitted sequencing is to ensure that the order of the sequences is correct. This is important because it ensures that the sequences are processed in the correct order and that the data is not corrupted. By enforcing permitted sequencing, we can prevent data corruption and ensure that the sequences are processed in the correct order.

### Explanation:
Enforcing permitted sequencing is important because it ensures that the order of the sequences is correct. This is important because it ensures that the sequences are processed in the correct order and that the data is not corrupted. By enforcing permitted sequencing, we can prevent data corruption and ensure that the sequences are processed in the correct order. This is important because it ensures that the data is accurate and that the sequences are processed in the correct order
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What does FDA/GxP require for changes made to electronic records?
Base A: Electronic records are required to be complete and accurate. Any changes made to electronic records should be reflected in a change control system. Electronic records should be maintained in a manner that ensures that they remain complete and accurate over time. This includes ensuring that any changes made to electronic records are properly documented and that the records are backed up regularly to prevent data loss. Electronic records should also be stored in a manner that ensures that they remain accessible and retrievable over time.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How often should operational system checks be reviewed?
Base A: The operational system checks should be reviewed every 3 months.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What should be included in procedures for electronic records?
Base A: What should be included in procedures for electronic records?

### Explanation:
The procedures for electronic records should include the following:

1. The purpose of the record should be clearly stated.
2. The record should be accurate and complete.
3. The record should be kept in a secure location.
4. The record should be updated regularly.
5. The record should be destroyed when it is no longer needed.

### Answer:
What should be included in procedures for electronic records?

### Explanation:
The procedures for electronic records should include the following:

1. The purpose of the record should be clearly stated.
2. The record should be accurate and complete.
3. The record should be kept in a secure location.
4. The record should be updated regularly.
5
---
Q: Are audit trails optional under FDA/GxP regulations?
Base A: Audit trails are not optional under FDA/GxP regulations. The FDA's regulations on electronic records and electronic signatures, 21 CFR Part 11, require that electronic records and electronic signatures that are created, modified, maintained, archived, retrieved, or transmitted under any circumstances shall be kept and be able to be independently verified. To meet this requirement, the FDA requires that electronic records and electronic signatures be kept in an audit trail. The FDA's regulations on electronic records and electronic signatures are designed to ensure that electronic records are trustworthy and reliable. Audit trails are critical to meeting this goal because they allow for the independent verification of electronic records. Without audit trails, electronic records would be less trustworthy and reliable. Therefore, audit trails are not optional under FDA/G
---

In [39]:
model.enable_adapter_layers()

In [40]:
with open('base_answers.json', 'w') as f:
    json.dump(base_answers, f)
print("Saved base answers")

Saved base answers

In [41]:
def judge_answer(question, answer):
    prompt = f"""You are an expert FDA/GxP regulatory compliance evaluator.

Rate the following answer to a compliance question on a scale of 1-5:
1 = incorrect, irrelevant, or empty
2 = partially relevant but vague or inaccurate
3 = acceptable but generic, missing compliance-specific detail
4 = accurate and reasonably specific
5 = accurate, specific, and uses correct regulatory terminology

Question: {question}
Answer: {answer}

Respond with ONLY a single integer 1-5, nothing else."""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    try:
        return int(response.choices[0].message.content.strip())
    except:
        return None

In [42]:
base_scores = []
for item, answer in zip(test_data, base_answers):
    score = judge_answer(item['instruction'], answer)
    base_scores.append(score)
    print(f"{score} — {item['instruction'][:60]}")

print(f"\nBase model average: {sum(s for s in base_scores if s) / len(base_scores):.2f} / 5")

3 — What should an organization do to ensure compliance with aud
3 — What are operational system checks?
3 — What are the consequences of inadequate system validation?
3 — What are the consequences of not implementing authority chec
3 — Why are operational system checks important for compliance?
2 — Who is responsible for managing authority checks?
4 — How long must audit trail documentation be retained accordin
2 — How can I ensure that my procedures are effective?
3 — What actions should be taken to prepare for an inspection of
2 — What is the purpose of enforcing permitted sequencing?
4 — What does FDA/GxP require for changes made to electronic rec
2 — How often should operational system checks be reviewed?
2 — What should be included in procedures for electronic records
5 — Are audit trails optional under FDA/GxP regulations?

Base model average: 2.93 / 5

In [43]:
finetuned_scores = []
for item, answer in zip(test_data, finetuned_answers):
    score = judge_answer(item['instruction'], answer)
    finetuned_scores.append(score)
    print(f"{score} — {item['instruction'][:60]}")

print(f"\nFine-tuned model average: {sum(s for s in finetuned_scores if s) / len(finetuned_scores):.2f} / 5")

4 — What should an organization do to ensure compliance with aud
4 — What are operational system checks?
3 — What are the consequences of inadequate system validation?
4 — What are the consequences of not implementing authority chec
3 — Why are operational system checks important for compliance?
3 — Who is responsible for managing authority checks?
4 — How long must audit trail documentation be retained accordin
3 — How can I ensure that my procedures are effective?
3 — What actions should be taken to prepare for an inspection of
4 — What is the purpose of enforcing permitted sequencing?
4 — What does FDA/GxP require for changes made to electronic rec
3 — How often should operational system checks be reviewed?
4 — What should be included in procedures for electronic records
4 — Are audit trails optional under FDA/GxP regulations?

Fine-tuned model average: 3.57 / 5

In [44]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

Unsloth: Already have LoRA adapters! We shall skip this step.

In [45]:
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 120,       # doubled from 60
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/77 [00:00<?, ? examples/s]

In [46]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 77 | Num Epochs = 12 | Total steps = 120
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)

Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-120/tokenizer_config.json.

In [47]:
FastLanguageModel.for_inference(model)

finetuned_answers_v2 = []
for item in test_data:
    answer = generate_answer(item['instruction'], item.get('input', ''))
    finetuned_answers_v2.append(answer)
    print("Q:", item['instruction'])
    print("Fine-tuned A:", answer)
    print("---")

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What should an organization do to ensure compliance with audit trail requirements?
Fine-tuned A: Organization should implement policies and procedures to ensure that all actions generating audit trails are documented, that records are accurate and complete, and that they can demonstrate compliance with audit trail regulations at any time.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are operational system checks?
Fine-tuned A: Operational system checks are mechanisms used to ensure that all operational steps are performed in the correct order, thereby minimizing the risk of deviations that could affect product quality.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are the consequences of inadequate system validation?
Fine-tuned A: Inadequate system validation can lead to non-compliance, potential legal issues, and increased risks to patient safety and data integrity.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What are the consequences of not implementing authority checks?
Fine-tuned A: Not implementing authority checks can lead to unauthorized access and actions, resulting in compliance violations, data integrity issues, and potential legal repercussions.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: Why are operational system checks important for compliance?
Fine-tuned A: Operational system checks are important for compliance as they help ensure that processes are followed correctly, thereby minimizing the risk of non-compliance and enhancing overall process reliability.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: Who is responsible for managing authority checks?
Fine-tuned A: The organization is responsible for implementing and managing authority checks to ensure that only authorized individuals have access to the system.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How long must audit trail documentation be retained according to FDA/GxP regulations?
Fine-tuned A: Audit trail documentation must be retained for a period of at least one year, in compliance with FDA/GxP regulations.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How can I ensure that my procedures are effective?
Fine-tuned A: To ensure that your procedures are effective, regularly monitor their performance, review audit logs, and take corrective actions as necessary to address any deviations.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What actions should be taken to prepare for an inspection of electronic records?
Fine-tuned A: To prepare for an inspection of electronic records, agency personnel should ensure that the records are accurate and complete, and that all systems used to create, modify, maintain, or transmit these records are compliant with regulatory requirements.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What is the purpose of enforcing permitted sequencing?
Fine-tuned A: Enforcing permitted sequencing is purpose is to ensure that operations are conducted in the correct order, thus maintaining the integrity of the process and enhancing overall reliability.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What does FDA/GxP require for changes made to electronic records?
Fine-tuned A: FDA/GxP requires that changes to electronic records are documented with audit trails that accurately reflect the date and time of actions taken.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: How often should operational system checks be reviewed?
Fine-tuned A: Operational system checks should be reviewed regularly, at least annually, or whenever there are changes in processes or regulatory requirements to ensure they remain effective and compliant.
---

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Q: What should be included in procedures for electronic records?
Fine-tuned A: Procedures for electronic records should include system validation, access restrictions, the ability to generate accurate copies, and the implementation of controls to ensure the integrity of the records.
---
Q: Are audit trails optional under FDA/GxP regulations?
Fine-tuned A: No, audit trails are mandatory under FDA/GxP regulations to ensure compliance and adherence to strict protocols for maintaining electronic records.
---

In [48]:
finetuned_scores_v2 = []
for item, answer in zip(test_data, finetuned_answers_v2):
    score = judge_answer(item['instruction'], answer)
    finetuned_scores_v2.append(score)
    print(f"{score} — {item['instruction'][:60]}")

print(f"\nFine-tuned v2 average: {sum(s for s in finetuned_scores_v2 if s) / len(finetuned_scores_v2):.2f} / 5")

3 — What should an organization do to ensure compliance with aud
4 — What are operational system checks?
3 — What are the consequences of inadequate system validation?
4 — What are the consequences of not implementing authority chec
3 — Why are operational system checks important for compliance?
4 — Who is responsible for managing authority checks?
2 — How long must audit trail documentation be retained accordin
4 — How can I ensure that my procedures are effective?
3 — What actions should be taken to prepare for an inspection of
3 — What is the purpose of enforcing permitted sequencing?
4 — What does FDA/GxP require for changes made to electronic rec
4 — How often should operational system checks be reviewed?
4 — What should be included in procedures for electronic records
5 — Are audit trails optional under FDA/GxP regulations?

Fine-tuned v2 average: 3.57 / 5

In [49]:
import os
for root, dirs, files in os.walk('outputs'):
    for f in files:
        print(os.path.join(root, f))

outputs/README.md
outputs/checkpoint-120/training_args.bin
outputs/checkpoint-120/adapter_config.json
outputs/checkpoint-120/README.md
outputs/checkpoint-120/adapter_model.safetensors
outputs/checkpoint-120/optimizer.pt
outputs/checkpoint-120/scheduler.pt
outputs/checkpoint-120/trainer_state.json
outputs/checkpoint-120/scaler.pt
outputs/checkpoint-120/tokenizer_config.json
outputs/checkpoint-120/tokenizer.json
outputs/checkpoint-120/rng_state.pth
outputs/checkpoint-60/training_args.bin
outputs/checkpoint-60/adapter_config.json
outputs/checkpoint-60/README.md
outputs/checkpoint-60/adapter_model.safetensors
outputs/checkpoint-60/optimizer.pt
outputs/checkpoint-60/scheduler.pt
outputs/checkpoint-60/trainer_state.json
outputs/checkpoint-60/scaler.pt
outputs/checkpoint-60/tokenizer_config.json
outputs/checkpoint-60/tokenizer.json
outputs/checkpoint-60/rng_state.pth

In [50]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
    ),
)

trainer_stats = trainer.train()

Unsloth: Already have LoRA adapters! We shall skip this step.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 77 | Num Epochs = 6 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)

In [51]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

==((====))==  Unsloth 2026.9.11: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3-8b-bnb-4bit as a legacy tokenizer.

In [52]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
    ),
)

trainer_stats = trainer.train()

Unsloth: Already have LoRA adapters! We shall skip this step.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 77 | Num Epochs = 6 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)

In [53]:
FastLanguageModel.for_inference(model)

finetuned_answers_final = []
for item in test_data:
    answer = generate_answer(item['instruction'], item.get('input', ''))
    finetuned_answers_final.append(answer)

finetuned_scores_final = []
for item, answer in zip(test_data, finetuned_answers_final):
    score = judge_answer(item['instruction'], answer)
    finetuned_scores_final.append(score)
    print(f"{score} — {item['instruction'][:60]}")

print(f"\nFinal fine-tuned average: {sum(s for s in finetuned_scores_final if s) / len(finetuned_scores_final):.2f} / 5")

Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=150) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

4 — What should an organization do to ensure compliance with aud
4 — What are operational system checks?
3 — What are the consequences of inadequate system validation?
4 — What are the consequences of not implementing authority chec
3 — Why are operational system checks important for compliance?
3 — Who is responsible for managing authority checks?
4 — How long must audit trail documentation be retained accordin
4 — How can I ensure that my procedures are effective?
3 — What actions should be taken to prepare for an inspection of
4 — What is the purpose of enforcing permitted sequencing?
4 — What does FDA/GxP require for changes made to electronic rec
3 — How often should operational system checks be reviewed?
4 — What should be included in procedures for electronic records
4 — Are audit trails optional under FDA/GxP regulations?

Final fine-tuned average: 3.64 / 5

In [54]:
with open('finetuned_answers.json', 'w') as f:
    json.dump(finetuned_answers_final, f)
print("Saved final fine-tuned answers")

Saved final fine-tuned answers

In [55]:
!pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.13/dist-packages (1.29.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (3.32.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)

In [57]:
from huggingface_hub import login
login()

In [58]:
model.push_to_hub("rajeshvctec/llama3-8b-fda-gxp-qlora", token=True)
tokenizer.push_to_hub("rajeshvctec/llama3-8b-fda-gxp-qlora", token=True)

README.md:   0%|          | 0.00/556 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          |  559kB /  168MB

Saved model to https://huggingface.co/rajeshvctec/llama3-8b-fda-gxp-qlora

Unsloth: Restored added_tokens_decoder metadata in /tmp/tmp8calttq2/tokenizer_config.json.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp8calttq2/tokenizer.json: 100%|##########| 17.2MB / 17.2MB